### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by VyZi** [nlitsme/zipdump#2]
I have wanted to use this for some big zips that are on the web, some sites however don't like the default headers from requests

No matter how I have tried to add custom headers, they didn't seem to work, and I can't really figure out how to do it

**Comment by nlitsme** [comment]
What site specifically are you talking about?

**Comment by VyZi** [comment]
Well basically any site that doesn't like the default headers requests uses

I'm not really sure how to use custom headers with this code

**Comment by nlitsme** [comment]
I added a `-H "Your-Header: value"`  option, does this help?

**Comment by VyZi** [comment]
It works now, thanks!

**Comment by VyZi** [comment]
By the way, I'm not really sure how to save files from the zip, after I specify a file from a directory the code stops

**Comment by nlitsme** [comment]
Can you make a new issue.  That seems like a different subject.  And add an example and what output do you get?
