### ISSUE TITLE
Saving files from zip

### ISSUE THREAD

**Issue by VyZi** [nlitsme/zipdump#3]
This is most likely not a problem with the code

I'm unsure how to save files from a zip

I add the --save option and the path to the file and nothing really happens, no output and the program doesn't finish too, it just stops

**Comment by nlitsme** [comment]
Can you tell me the exact commandline you are using?
And post a screenshot, from which you are led to believe 'hothing happens'?

**Comment by VyZi** [comment]
Well the exact command is

zipdump.py -q -H "Header" url --save folder/folder/file.ext

Why I think it stops is pretty simple, when a python program finishes working python returns [Program Finished], however here the program just endlessly doesn't output anything

**Comment by nlitsme** [comment]
I am guessing that is not the exact command line, since 'url'  doesn't look like a real url.
Are you sure that 'folder/folder/file.ext' is in the .zip?

python never says 'Program Finished'  I am not sure where you saw that.

it could be that the download takes longer than expected.

**Comment by VyZi** [comment]
That's right, I gave it as an example of what I type

Yeah I'm sure

Yeah you are right, I think it only happens in the idle, but still, when running a python script from cmd, after finishing it gets back to the typing prompt (you know, "Letter:\Windows\system32>" or the one displayed on Linux), in this case it doesn't happen

I'm not sure but that might be the case too

**Comment by nlitsme** [comment]
Since you appear to refuse to say what exactly you type, I will close this ticket.
